name: apiClient
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  http: ^1.2.0
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.1.0
  retrofit_generator: ^10.0.2

  storage:
    path: ../storage

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^6.0.0
  json_serializable: ^6.7.1
  lints: ^6.0.0
  very_good_analysis: ^9.0.0